name: dart_swagger_to_api_client
description: Generate type-safe HTTP API clients from OpenAPI/Swagger specs for Dart and Flutter.
version: 1.0.0

homepage: https://github.com/AlexGalitsky/dart_swagger_to_api_client
repository: https://github.com/AlexGalitsky/dart_swagger_to_api_client
issue_tracker: https://github.com/AlexGalitsky/dart_swagger_to_api_client/issues

screenshots:
  - description: 'Dart - Swagger to API client logo.'
    path: images/logo.png

topics:
  - openapi
  - swagger
  - code-generator
  - codegen
  - http-client

environment:
  sdk: ^3.11.0

dependencies:
  http: ^1.6.0
  yaml: ^3.1.3
  path: ^1.9.1
  args: ^2.7.0
  dio: ^5.4.0
  meta: ^1.14.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  coverage: ^1.9.0
