name: dart_swagger_to_api_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.0

dependencies:
  http: ^1.6.0
  yaml: ^3.1.3
  path: ^1.9.1
  args: ^2.7.0
  dio: ^5.4.0
  meta: ^1.14.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
